name: CI

on:
  pull_request:
    branches:[main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dentro del paso
        uses: actions/checkout@v3
      - name: Instala java
        uses: actions/setup-java@v3
        with:
          distribution:'temurin'
          java-version:'17'
      - name: Validar Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build