name: CI

on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el proyecto
        uses: actions/checkout@v3
      - name: Instala java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
